server:
  port: 8080
spring:
  application:
    name: sf-service
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${sf.db.host}:3306/sf?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${sf.db.pw}
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000
      password: 0721~Forever
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    com.nonameplz.sfservice: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.nonameplz.sfservice.controller
# knife4j的增强配置
knife4j:
  enable: true
  setting:
    language: zh_cn
  openapi:
    title: 'shoppingFree平台接口文档'
    description: "shoppingFree平台接口文档"
    email: sh68589500@outlook.com
    authName: Noname
    url: noURL
    version: v1.0.0

sf:
  jwt:
    location: classpath:sf.jks
    alias: sf
    password: 0721~Forever
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /users/register
      - /items/**
      - /testing/**

aliyun:
  oss:
    endpoint: https://oss-cn-shanghai.aliyuncs.com
    bucketName: image-container